name: hex-assay-analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyter=1.0.0
  - pip=23.2.1
  - pre-commit=3.5.0
  - python=3.11
  - ruff=0.4.8
  - matplotlib=3.8.2
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.14.0
  - scikit-learn=1.6.0
  - statsmodels=0.14.2
  - pip:
      - arcadia_pycolor==0.5.1
